services:
  ssl-proxy:
    image: nginx:alpine
    container_name: ssl_proxy_preprod
    restart: unless-stopped
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /data/docker/internetmantes/certs:/etc/nginx/ssl:ro
    networks:
      - proxy-network
      - drupal-network
      - intranet-network
      - nextjs-network

networks:
  proxy-network:
    driver: bridge
  drupal-network:
    external: true
    name: internet-mlj-preprod_default
  intranet-network:
    external: true
    name: intra-mlj-preprod_drupal
  nextjs-network:
    external: true
    name: stagging_default