services:
  ssl-proxy:
    image: nginx:alpine
    container_name: ssl_proxy_local
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxy-network
      - internet-network
      - intranet-network

networks:
  proxy-network:
    driver: bridge
  internet-network:
    external: true
    name: internet-mlj_default
  intranet-network:
    external: true
    name: infra-mlj_local_drupal