services:
  ssl-proxy:
    image: nginx:alpine
    container_name: ssl_proxy_production
    restart: always
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - proxy-network
      - internet-network
      - intranet-network

networks:
  proxy-network:
    driver: bridge
  internet-network:
    external: true
    name: internet-mlj_production_default
  intranet-network:
    external: true
    name: infra-mlj_production_drupal