services:
  ssl-proxy:
    image: nginx:alpine
    container_name: ssl_proxy_production
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx.conf/default.conf:/etc/nginx/nginx.conf:ro
      - ../ssl:/etc/nginx/ssl:ro
    networks:
      - proxy-network
      - internet-network
      - intranet-network
      - nextjs-network

networks:
  proxy-network:
    driver: bridge
  internet-network:
    external: true
    name: internet-mlj-prod_default
  intranet-network:
    external: true
    name: production_drupal
  nextjs-network:
    external: true
    name: production_default
